package testcases;

import java.util.*;
import javax.mail.*;

import org.testng.annotations.Test;
import org.testng.asserts.SoftAssert;

import toplevel.D;
import toplevel.Helper;

public class Temp {
	
	@Test
    public static void email() {
		String[] mailsE = {
				"TEST: <> Gekocht, kavel voor XXXXXXADV - XXXXXXADV-Campaign / XXXXXXBuyNow, editie:    . OrdergeplaatstMediabureau:XXXXXXMBAdverteerder:XXXXXXADVCampagne:XXXXXXADV-Campaign  Uitgever:XXXXXXUGTitel:XXXXXXBuyNow,editiePublicatiedatum:dd-mm-yyyyFormaat:CD101V-VolledigepaginaPositie:Cover2Deadlinemateriaal:dd-mm-yyyy  Bruto:€ 3.150,00Contractkorting:€ 1.575,00Contractkorting%:50,00Volumekorting:€ 0,00Volumekorting%:0,00  Orderprijs(exBTW):€ 1.575,00AdoptiqOrderNr:NNNN   Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmet support@adoptiq.com. Voorinhoudelijkevragenkuntudesgewenstcontactopnemenmetdeuitgever. .OrdergeplaatstMediabureau:XXXXXXMBAdverteerder:XXXXXXADVCampagne:XXXXXXADV-CampaignUitgever:XXXXXXUGTitel:XXXXXXBuyNow,editiePublicatiedatum:dd-mm-yyyyFormaat:CD101V-VolledigepaginaPositie:Cover2Deadlinemateriaal:dd-mm-yyyyBruto:&euro;3.150,00Contractkorting:&euro;1.575,00Contractkorting%:50,00Volumekorting:&euro;0,00Volumekorting%:0,00Orderprijs(exBTW):&euro;1.575,00AdoptiqOrderNr:NNNNDezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmetsupport@adoptiq.com.Voorinhoudelijkevragenkuntudesgewenstcontactopnemenmetdeuitgever.",
"TEST: <> Gekocht, kavel voor XXXXXXADV - XXXXXXADV-Campaign / XXXXXXBuyNow, editie:    . OrdergeplaatstMediabureau:XXXXXXMBAdverteerder:XXXXXXADVCampagne:XXXXXXADV-Campaign  Uitgever:XXXXXXUGTitel:XXXXXXBuyNow,editiePublicatiedatum:dd-mm-yyyyFormaat:CD101V-VolledigepaginaPositie:Cover2Deadlinemateriaal:dd-mm-yyyy  Bruto:€ 3.150,00Contractkorting:€ 1.575,00Contractkorting%:50,00Volumekorting:€ 0,00Volumekorting%:0,00  Orderprijs(exBTW):€ 1.575,00AdoptiqOrderNr:NNNN   Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmet support@adoptiq.com. Voorinhoudelijkevragenkuntudesgewenstcontactopnemenmetdeuitgever. .OrdergeplaatstMediabureau:XXXXXXMBAdverteerder:XXXXXXADVCampagne:XXXXXXADV-CampaignUitgever:XXXXXXUGTitel:XXXXXXBuyNow,editiePublicatiedatum:dd-mm-yyyyFormaat:CD101V-VolledigepaginaPositie:Cover2Deadlinemateriaal:dd-mm-yyyyBruto:&euro;3.150,00Contractkorting:&euro;1.575,00Contractkorting%:50,00Volumekorting:&euro;0,00Volumekorting%:0,00Orderprijs(exBTW):&euro;1.575,00AdoptiqOrderNr:NNNNDezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmetsupport@adoptiq.com.Voorinhoudelijkevragenkuntudesgewenstcontactopnemenmetdeuitgever.",
"TEST: <> Order voor XXXXXXBuyNow, editie:    . OrdergeplaatstMediabureau:XXXXXXMBAdverteerder:XXXXXXADVCampagne:XXXXXXADV-Campaign  Uitgever:XXXXXXUGTitel:XXXXXXBuyNow,editiePublicatiedatum:dd-mm-yyyyFormaat:CD101V-VolledigepaginaPositie:Cover2Deadlinemateriaal:dd-mm-yyyy  Bruto:€ 3.150,00Contractkorting:€ 1.575,00Contractkorting%:50,00Volumekorting:€ 0,00Volumekorting%:0,00  Orderprijs(exBTW):€ 1.575,00AdoptiqOrderNr:NNNN   Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmet support@adoptiq.com. Voorinhoudelijkevragenkuntudesgewenstcontactopnemenmet TestMediaAgencyempl,autotestAdoptiq@gmail.com.  .OrdergeplaatstMediabureau:XXXXXXMBAdverteerder:XXXXXXADVCampagne:XXXXXXADV-CampaignUitgever:XXXXXXUGTitel:XXXXXXBuyNow,editiePublicatiedatum:dd-mm-yyyyFormaat:CD101V-VolledigepaginaPositie:Cover2Deadlinemateriaal:dd-mm-yyyyBruto:&euro;3.150,00Contractkorting:&euro;1.575,00Contractkorting%:50,00Volumekorting:&euro;0,00Volumekorting%:0,00Orderprijs(exBTW):&euro;1.575,00AdoptiqOrderNr:NNNNDezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmetsupport@adoptiq.com.VoorinhoudelijkevragenkuntudesgewenstcontactopnemenmetTestMediaAgencyempl,autotestAdoptiq@gmail.com.",
"TEST: Bestelling 2 Order(s) XXXXXXADV2    . Order(s)geplaatst(ziebijlage)Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBUitgever:XXXXXXRes2  Bruto:€ 8.250,00(Totale)contractkorting:€ 0,00(Totale)volumekorting:€ 2.062,50  Totaalbedragingeslotenorder(s)(exBTW):€ 6.187,50   Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmet support@adoptiq.com. Voorinhoudelijkevragengraagcontactopnemenmetdeuitgever. .Order(s)geplaatst(ziebijlage)Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBUitgever:XXXXXXRes2Bruto:&euro;8.250,00(Totale)contractkorting:&euro;0,00(Totale)volumekorting:&euro;2.062,50Totaalbedragingeslotenorder(s)(exBTW):&euro;6.187,50Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmetsupport@adoptiq.com.Voorinhoudelijkevragengraagcontactopnemenmetdeuitgever.",
"TEST: Bestelling 2 Order(s) XXXXXXADV2    . Order(s)geplaatst(ziebijlage)Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBUitgever:XXXXXXRes2  Bruto:€ 8.250,00(Totale)contractkorting:€ 0,00(Totale)volumekorting:€ 2.062,50  Totaalbedragingeslotenorder(s)(exBTW):€ 6.187,50   Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmet support@adoptiq.com. VoorinhoudelijkevragenkuntudesgewenstcontactopnemenmetTestMediaAgencyempl,autotestAdoptiq@gmail.com. .Order(s)geplaatst(ziebijlage)Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBUitgever:XXXXXXRes2Bruto:&euro;8.250,00(Totale)contractkorting:&euro;0,00(Totale)volumekorting:&euro;2.062,50Totaalbedragingeslotenorder(s)(exBTW):&euro;6.187,50Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmetsupport@adoptiq.com.VoorinhoudelijkevragenkuntudesgewenstcontactopnemenmetTestMediaAgencyempl,autotestAdoptiq@gmail.com.",
"TEST: Bestelling 2 Order(s)    . Order(s)geplaatst(ziebijlage)Adverteerder:XXXXXXADV2Uitgever:XXXXXXRes2  Bruto:€ 8.250,00(Totale)contractkorting:€ 0,00(Totale)volumekorting:€ 2.062,50  Totaalbedragingeslotenorder(s)(exBTW):€ 6.187,50   Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmet support@adoptiq.com. Voorinhoudelijkevragengraagcontactopnemenmetdeuitgever. .Order(s)geplaatst(ziebijlage)Adverteerder:XXXXXXADV2Uitgever:XXXXXXRes2Bruto:&euro;8.250,00(Totale)contractkorting:&euro;0,00(Totale)volumekorting:&euro;2.062,50Totaalbedragingeslotenorder(s)(exBTW):&euro;6.187,50Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmetsupport@adoptiq.com.Voorinhoudelijkevragengraagcontactopnemenmetdeuitgever.",
"TEST: <> XXXXXXADV2    . VerzamelprivateseatordergeplaatstIngegevenreferentiecode:Uitgever:XXXXXXRes2  Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBCampagne:XXXXXXADV2-Campaign  Deuitgeverzalreagerenmetbevestigingvandeafgesproken(overall)prijs(ziebijlage)   Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmet support@adoptiq.com.Voorinhoudelijkevragengraagcontactopnemenmetdeuitgever. .VerzamelprivateseatordergeplaatstIngegevenreferentiecode:Uitgever:XXXXXXRes2Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBCampagne:XXXXXXADV2-CampaignDeuitgeverzalreagerenmetbevestigingvandeafgesproken(overall)prijs(ziebijlage)Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmetsupport@adoptiq.com.Voorinhoudelijkevragengraagcontactopnemenmetdeuitgever.",
"TEST: <> XXXXXXADV2    . VerzamelprivateseatordergeplaatstIngegevenreferentiecode:Uitgever:XXXXXXRes2  Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBCampagne:XXXXXXADV2-Campaign  Deuitgeverzalreagerenmetbevestigingvandeafgesproken(overall)prijs(ziebijlage)   Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmet support@adoptiq.com.Voorinhoudelijkevragengraagcontactopnemenmetdeuitgever. .VerzamelprivateseatordergeplaatstIngegevenreferentiecode:Uitgever:XXXXXXRes2Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBCampagne:XXXXXXADV2-CampaignDeuitgeverzalreagerenmetbevestigingvandeafgesproken(overall)prijs(ziebijlage)Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmetsupport@adoptiq.com.Voorinhoudelijkevragengraagcontactopnemenmetdeuitgever.",
"TEST: Bestelling (private seat) verzamelorder o.b.v. referentiecode    . VerzamelprivateseatordergeplaatstIngegevenreferentiecode:Uitgever:XXXXXXRes2  Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBCampagne:XXXXXXADV2-Campaign  HandelopAdoptiqdeverzamelorderafviaingavevandeafgesproken(overall)prijs (ziebijlage)   Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmet support@adoptiq.com. VoorinhoudelijkevragenkuntudesgewenstcontactopnemenmetTestMediaAgencyempl,autotestAdoptiq@gmail.com. .VerzamelprivateseatordergeplaatstIngegevenreferentiecode:Uitgever:XXXXXXRes2Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBCampagne:XXXXXXADV2-CampaignHandelopAdoptiqdeverzamelorderafviaingavevandeafgesproken(overall)prijs(ziebijlage)Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmetsupport@adoptiq.com.VoorinhoudelijkevragenkuntudesgewenstcontactopnemenmetTestMediaAgencyempl,autotestAdoptiq@gmail.com.",
"TEST: <> Terugkoppeling, (private seat) kavel voor XXXXXXADV2 - XXXXXXADV2-Campaign / XXXXXXBuyNow2, editie:    . PrivateseatorderterugkoppelingReferentiecodevandeuitgever:Uitgeverordernummer:Prijsuitgever:€2.500,00Kortinguitgever:50,00  Uwreferentiecode:BulkDeal1Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBCampagne:XXXXXXADV2-Campaign  Uitgever:XXXXXXRes2Titel:XXXXXXBuyNow2,editiePublicatiedatum:dd-mm-yyyyFormaat:CD101V-VolledigepaginaPositie:Pagina4-5Deadlinemateriaal:dd-mm-yyyy  AdoptiqOrderNr:NNNN  Deuitgeverheeftdezeafgehandelddooringavevandeafgesprokenprijs   Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmet support@adoptiq.com. Voorinhoudelijkevragenkuntudesgewenstcontactopnemenmetdeuitgever: TestPublisherempl,autotestAdoptiq@gmail.com. .PrivateseatorderterugkoppelingReferentiecodevandeuitgever:Uitgeverordernummer:Prijsuitgever:&euro;2.500,00Kortinguitgever:50,00Uwreferentiecode:BulkDeal1Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBCampagne:XXXXXXADV2-CampaignUitgever:XXXXXXRes2Titel:XXXXXXBuyNow2,editiePublicatiedatum:dd-mm-yyyyFormaat:CD101V-VolledigepaginaPositie:Pagina4-5Deadlinemateriaal:dd-mm-yyyyAdoptiqOrderNr:NNNNDeuitgeverheeftdezeafgehandelddooringavevandeafgesprokenprijsDezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmetsupport@adoptiq.com.Voorinhoudelijkevragenkuntudesgewenstcontactopnemenmetdeuitgever:TestPublisherempl,autotestAdoptiq@gmail.com.",
"TEST: <> Terugkoppeling, (private seat) kavel voor XXXXXXADV2 - XXXXXXADV2-Campaign / XXXXXXBuyNow2, editie:    . PrivateseatorderterugkoppelingReferentiecodevandeuitgever:Uitgeverordernummer:Prijsuitgever:€2.500,00Kortinguitgever:50,00  Uwreferentiecode:BulkDeal1Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBCampagne:XXXXXXADV2-Campaign  Uitgever:XXXXXXRes2Titel:XXXXXXBuyNow2,editiePublicatiedatum:dd-mm-yyyyFormaat:CD101V-VolledigepaginaPositie:Pagina4-5Deadlinemateriaal:dd-mm-yyyy  AdoptiqOrderNr:NNNN  Deuitgeverheeftdezeafgehandelddooringavevandeafgesprokenprijs   Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmet support@adoptiq.com. Voorinhoudelijkevragenkuntudesgewenstcontactopnemenmetdeuitgever: TestPublisherempl,autotestAdoptiq@gmail.com. .PrivateseatorderterugkoppelingReferentiecodevandeuitgever:Uitgeverordernummer:Prijsuitgever:&euro;2.500,00Kortinguitgever:50,00Uwreferentiecode:BulkDeal1Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBCampagne:XXXXXXADV2-CampaignUitgever:XXXXXXRes2Titel:XXXXXXBuyNow2,editiePublicatiedatum:dd-mm-yyyyFormaat:CD101V-VolledigepaginaPositie:Pagina4-5Deadlinemateriaal:dd-mm-yyyyAdoptiqOrderNr:NNNNDeuitgeverheeftdezeafgehandelddooringavevandeafgesprokenprijsDezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmetsupport@adoptiq.com.Voorinhoudelijkevragenkuntudesgewenstcontactopnemenmetdeuitgever:TestPublisherempl,autotestAdoptiq@gmail.com.",
"TEST: <> Terugkoppeling, (private seat) kavel voor XXXXXXADV2 - XXXXXXADV2-Campaign / XXXXXXBuyNow2, editie:    . PrivateseatorderterugkoppelingReferentiecodevandeuitgever:Uitgeverordernummer:Prijsuitgever:€3.000,00Kortinguitgever:40,00  Uwreferentiecode:BulkDeal1Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBCampagne:XXXXXXADV2-Campaign  Uitgever:XXXXXXRes2Titel:XXXXXXBuyNow2,editiePublicatiedatum:dd-mm-yyyyFormaat:CD101V-VolledigepaginaPositie:Pagina3Deadlinemateriaal:dd-mm-yyyy  AdoptiqOrderNr:NNNN  Deuitgeverheeftdezeafgehandelddooringavevandeafgesprokenprijs   Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmet support@adoptiq.com. Voorinhoudelijkevragenkuntudesgewenstcontactopnemenmetdeuitgever: TestPublisherempl,autotestAdoptiq@gmail.com. .PrivateseatorderterugkoppelingReferentiecodevandeuitgever:Uitgeverordernummer:Prijsuitgever:&euro;3.000,00Kortinguitgever:40,00Uwreferentiecode:BulkDeal1Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBCampagne:XXXXXXADV2-CampaignUitgever:XXXXXXRes2Titel:XXXXXXBuyNow2,editiePublicatiedatum:dd-mm-yyyyFormaat:CD101V-VolledigepaginaPositie:Pagina3Deadlinemateriaal:dd-mm-yyyyAdoptiqOrderNr:NNNNDeuitgeverheeftdezeafgehandelddooringavevandeafgesprokenprijsDezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmetsupport@adoptiq.com.Voorinhoudelijkevragenkuntudesgewenstcontactopnemenmetdeuitgever:TestPublisherempl,autotestAdoptiq@gmail.com.",
"TEST: <> Terugkoppeling, (private seat) kavel voor XXXXXXADV2 - XXXXXXADV2-Campaign / XXXXXXBuyNow2, editie:    . PrivateseatorderterugkoppelingReferentiecodevandeuitgever:Uitgeverordernummer:Prijsuitgever:€3.000,00Kortinguitgever:40,00  Uwreferentiecode:BulkDeal1Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBCampagne:XXXXXXADV2-Campaign  Uitgever:XXXXXXRes2Titel:XXXXXXBuyNow2,editiePublicatiedatum:dd-mm-yyyyFormaat:CD101V-VolledigepaginaPositie:Pagina3Deadlinemateriaal:dd-mm-yyyy  AdoptiqOrderNr:NNNN  Deuitgeverheeftdezeafgehandelddooringavevandeafgesprokenprijs   Dezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmet support@adoptiq.com. Voorinhoudelijkevragenkuntudesgewenstcontactopnemenmetdeuitgever: TestPublisherempl,autotestAdoptiq@gmail.com. .PrivateseatorderterugkoppelingReferentiecodevandeuitgever:Uitgeverordernummer:Prijsuitgever:&euro;3.000,00Kortinguitgever:40,00Uwreferentiecode:BulkDeal1Adverteerder:XXXXXXADV2Mediabureau:XXXXXXMBCampagne:XXXXXXADV2-CampaignUitgever:XXXXXXRes2Titel:XXXXXXBuyNow2,editiePublicatiedatum:dd-mm-yyyyFormaat:CD101V-VolledigepaginaPositie:Pagina3Deadlinemateriaal:dd-mm-yyyyAdoptiqOrderNr:NNNNDeuitgeverheeftdezeafgehandelddooringavevandeafgesprokenprijsDezeemailisautomatischgegenereerd.Heeftuvragenoverderedenwaaromudezeontvangtneemdancontactopmetsupport@adoptiq.com.Voorinhoudelijkevragenkuntudesgewenstcontactopnemenmetdeuitgever:TestPublisherempl,autotestAdoptiq@gmail.com.",
};
				
		SoftAssert softAssert = new SoftAssert();
		String[] mails = new String[69];
		String credential = Helper.credential;
        Properties props = new Properties();
        props.setProperty("mail.store.protocol", "imaps");
        try {
            Session session = Session.getInstance(props, null);
            Store store = session.getStore();
            store.connect("imap.gmail.com", D.EMAIL, D.EmailPass);
            Folder inbox = store.getFolder("INBOX");
            inbox.open(Folder.READ_ONLY);
            int numberOfEmails = inbox.getMessageCount();
            System.out.println(numberOfEmails);
            
            if(numberOfEmails > 0){
            Message[] emails = inbox.getMessages();
            for(int i = 0; i < numberOfEmails; i++){
            	Address[] ad = emails[i].getFrom();
            	if(ad[0].toString().equalsIgnoreCase("system@adoptiq.com")){
            		StringBuilder sb = new StringBuilder(); 
            		sb.append(emails[i].getSubject().replaceAll("editie:.*", "editie:").replaceAll("TEST: .*]", "TEST:").replaceAll(credential, "XXXXXX").replaceAll("TEST: .* <>", "TEST: <>"));        		           		
            		//get content
                	Multipart mp = (Multipart) emails[i].getContent();
                	BodyPart bp = mp.getBodyPart(0);
                	Multipart mp2 = (Multipart) bp.getContent();               	
                	               	
                	for (int j = 0; j < mp2.getCount(); j++) {
                        BodyPart bodyPart = mp2.getBodyPart(j);
                        //<[^>]*>  html tag, \\s+ empty space and invisible character
                        sb.append(bodyPart.getContent().toString().replaceAll("<[^>]*>", "").replaceAll("\\s+", "").replaceAll("_*", "").replaceAll("&nbsp;", "").replaceAll(credential, "XXXXXX").replaceAll("\\d{2}-\\d{2}-\\d{4}", "dd-mm-yyyy").replaceAll("editie:[a-z]*\\d{2}[a-z]*\\d{4}", "editie").replaceAll("Nr:\\d+", "Nr:NNNN"));         
            	      }
                	mails[i] = sb.toString();
                	//System.out.println(mails[i]);
            		softAssert.assertEquals(mails[i],mailsE[i]); 

                  }
 //           	HashSet<String> set1 = new HashSet<String>(Arrays.asList(mails));
 //               HashSet<String> set2 = new HashSet<String>(Arrays.asList(mailsE));
                
 //               softAssert.assertTrue(set1.equals(set2));
              }
            }                   
            softAssert.assertAll();
            } catch (Exception mex) {
                  mex.printStackTrace();   
            }
	}
}	
